"""Async SQLAlchemy engine, session factory and ORM model for KEV entries."""

from datetime import date, datetime
from typing import AsyncGenerator, List, Optional

from sqlalchemy import BigInteger, Date, DateTime, Identity, String, Text, func
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from .config import get_settings

settings = get_settings()

engine = create_async_engine(settings.database_url, echo=False, pool_pre_ping=True)
SessionLocal = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


class KevVulnerability(Base):
    """One row per CVE in the CISA KEV catalog."""

    __tablename__ = "kev_vulnerabilities"

    # Auto-generated surrogate primary key
    # (BIGINT GENERATED BY DEFAULT AS IDENTITY in PostgreSQL)
    id: Mapped[int] = mapped_column(
        BigInteger, Identity(always=False), primary_key=True
    )

    # Natural/business key — unique, used as the upsert conflict target
    cve_id: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    vendor_project: Mapped[Optional[str]] = mapped_column(String(255))
    product: Mapped[Optional[str]] = mapped_column(String(255))
    vulnerability_name: Mapped[Optional[str]] = mapped_column(Text)
    date_added: Mapped[Optional[date]] = mapped_column(Date, index=True)
    short_description: Mapped[Optional[str]] = mapped_column(Text)
    required_action: Mapped[Optional[str]] = mapped_column(Text)
    due_date: Mapped[Optional[date]] = mapped_column(Date)
    known_ransomware_campaign_use: Mapped[Optional[str]] = mapped_column(String(32))
    notes: Mapped[Optional[str]] = mapped_column(Text)
    cwes: Mapped[Optional[List[str]]] = mapped_column(ARRAY(String(32)))

    # Catalog metadata captured at sync time
    catalog_version: Mapped[Optional[str]] = mapped_column(String(32))
    catalog_date_released: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True)
    )

    first_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


async def init_db() -> None:
    """Create tables if they do not exist (use Alembic for real migrations)."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def get_session() -> AsyncGenerator[AsyncSession, None]:
    async with SessionLocal() as session:
        yield session
