"""ai_fix_batch — multi-batch tracking for scope-aware AI fix generation.

Revision ID: 011_ai_fix_batch
Revises: 010_ai_credentials
Create Date: 2026-05-04

Why this exists
---------------
Until now, a run had at most one AI-fix batch in flight, and progress was
tracked entirely in Redis (or the in-memory fallback) keyed by ``run_id``.
The scope-aware feature lets the user fire multiple batches per run in
parallel (one for KEV, one for Criticals, one for a hand-picked
selection). The Redis-only model can't represent that — there is no
historical record once a batch's TTL expires, no way to list "all
batches that ran on run #42 in the last hour", and the run-id key
collides between concurrent batches.

This migration creates ``ai_fix_batch`` as the durable record of every
batch that has been (or is being) processed. Live progress still lives
in the progress store; this row holds the immutable "what was the scope,
when did it start, what was the outcome" data.

Schema
------
* ``id`` — UUID stored as a 36-char string (works on SQLite + Postgres).
* ``finding_ids_json`` — the resolved finding-id list, stored as a JSON
  array. Postgres has ``ARRAY``; SQLite doesn't. JSON is portable.
* ``scope_json`` — the original scope spec as posted by the client, kept
  for forensic / debugging value. JSON because the shape is open.
* ``status`` — mirrors :data:`app.ai.progress.ProgressStatus`.
* ``finding_ids_json`` is denormalised intentionally — the resolved
  set at batch-creation time is the source of truth for what the batch
  processed (findings can be deleted later).

Idempotency: existence-checked, mirrors 002 / 003 / 004 / 006-010.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "011_ai_fix_batch"
down_revision = "010_ai_credentials"
branch_labels = None
depends_on = None


def _table_exists(bind: sa.engine.Connection, name: str) -> bool:
    return name in sa.inspect(bind).get_table_names()


def _index_exists(bind: sa.engine.Connection, table: str, index: str) -> bool:
    try:
        return index in {ix["name"] for ix in sa.inspect(bind).get_indexes(table)}
    except sa.exc.NoSuchTableError:
        return False


def upgrade() -> None:
    bind = op.get_bind()

    if not _table_exists(bind, "ai_fix_batch"):
        op.create_table(
            "ai_fix_batch",
            # 36-char UUID (8-4-4-4-12 with dashes). Generated by the
            # application — keeps the migration DB-agnostic.
            sa.Column("id", sa.String(length=36), primary_key=True),
            sa.Column(
                "run_id",
                sa.Integer(),
                sa.ForeignKey("analysis_run.id", ondelete="CASCADE"),
                nullable=False,
            ),
            sa.Column("status", sa.String(length=24), nullable=False),
            # Human-readable scope description for the progress banner
            # ("Critical findings", "KEV findings", "Selected (12)"). NULL
            # for legacy "all findings" batches.
            sa.Column("scope_label", sa.String(length=120), nullable=True),
            # The original scope spec posted by the client, verbatim.
            sa.Column("scope_json", sa.JSON(), nullable=True),
            # Resolved finding-id set at batch-creation time. Kept even
            # if the underlying findings are later deleted, so audit /
            # rerun semantics remain stable.
            sa.Column("finding_ids_json", sa.JSON(), nullable=False),
            sa.Column("provider_name", sa.String(length=64), nullable=False),
            sa.Column("total", sa.Integer(), nullable=False, server_default=sa.text("0")),
            sa.Column(
                "cached_count",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("0"),
            ),
            sa.Column(
                "generated_count",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("0"),
            ),
            sa.Column(
                "failed_count",
                sa.Integer(),
                nullable=False,
                server_default=sa.text("0"),
            ),
            sa.Column(
                "cost_usd",
                sa.Numeric(10, 6),
                nullable=False,
                server_default=sa.text("0"),
            ),
            sa.Column("started_at", sa.String(), nullable=True),
            sa.Column("completed_at", sa.String(), nullable=True),
            sa.Column("created_at", sa.String(), nullable=False),
            sa.Column("last_error", sa.String(length=240), nullable=True),
        )

    if not _index_exists(bind, "ai_fix_batch", "ix_ai_fix_batch_run_status"):
        op.create_index(
            "ix_ai_fix_batch_run_status",
            "ai_fix_batch",
            ["run_id", "status"],
        )

    if not _index_exists(bind, "ai_fix_batch", "ix_ai_fix_batch_created_at"):
        op.create_index(
            "ix_ai_fix_batch_created_at",
            "ai_fix_batch",
            ["created_at"],
        )


def downgrade() -> None:
    bind = op.get_bind()
    if _table_exists(bind, "ai_fix_batch"):
        for ix in ("ix_ai_fix_batch_run_status", "ix_ai_fix_batch_created_at"):
            if _index_exists(bind, "ai_fix_batch", ix):
                op.drop_index(ix, table_name="ai_fix_batch")
        op.drop_table("ai_fix_batch")
