"""Frozen Phase 8 authorization catalogue seed.

Never edit this snapshot after revision 048 ships. Add a new versioned seed
module and migration for future catalogue changes.
"""

from __future__ import annotations

ALL_PERMISSIONS_V1 = (
    "analysis:read",
    "analysis:run",
    "component:read",
    "component:update",
    "dashboard:read",
    "lifecycle:override",
    "lifecycle:provider:read",
    "lifecycle:provider:sync",
    "lifecycle:provider:test",
    "lifecycle:provider:update",
    "lifecycle:read",
    "lifecycle:vendor-record:delete",
    "lifecycle:vendor-record:read",
    "lifecycle:vendor-record:write",
    "platform:admin",
    "platform:administrator:grant",
    "platform:administrator:read",
    "platform:administrator:revoke",
    "platform:authorization:manage",
    "platform:authorization:read",
    "platform:tenant:create",
    "platform:user:manage_status",
    "platform:user:read",
    "platform:user:write",
    "product:assign_sbom",
    "product:create",
    "product:delete",
    "product:manage_schedule",
    "product:read",
    "product:update",
    "project:create",
    "project:delete",
    "project:read",
    "project:update",
    "remediation:close",
    "remediation:read",
    "remediation:write",
    "sbom:delete",
    "sbom:export",
    "sbom:read",
    "sbom:repair:download",
    "sbom:repair:read",
    "sbom:repair:revalidate",
    "sbom:repair:search",
    "sbom:repair:update",
    "sbom:update",
    "sbom:upload",
    "schedule:read",
    "schedule:write",
    "tenant:settings:update",
    "tenant:user:invite",
    "tenant:user:read",
    "tenant:user:update",
    "vex:read",
    "vex:write",
)

ROLE_PERMISSIONS_V1 = {
    "PLATFORM_ADMIN": ALL_PERMISSIONS_V1,
    "TENANT_ADMIN": (
        "analysis:read",
        "analysis:run",
        "component:read",
        "component:update",
        "dashboard:read",
        "lifecycle:override",
        "lifecycle:provider:read",
        "lifecycle:provider:sync",
        "lifecycle:provider:test",
        "lifecycle:provider:update",
        "lifecycle:read",
        "lifecycle:vendor-record:delete",
        "lifecycle:vendor-record:read",
        "lifecycle:vendor-record:write",
        "product:assign_sbom",
        "product:create",
        "product:delete",
        "product:manage_schedule",
        "product:read",
        "product:update",
        "project:create",
        "project:delete",
        "project:read",
        "project:update",
        "remediation:close",
        "remediation:read",
        "remediation:write",
        "sbom:delete",
        "sbom:export",
        "sbom:read",
        "sbom:repair:download",
        "sbom:repair:read",
        "sbom:repair:revalidate",
        "sbom:repair:search",
        "sbom:repair:update",
        "sbom:update",
        "sbom:upload",
        "schedule:read",
        "schedule:write",
        "tenant:settings:update",
        "tenant:user:invite",
        "tenant:user:read",
        "tenant:user:update",
        "vex:read",
        "vex:write",
    ),
    "SECURITY_ANALYST": (
        "analysis:read",
        "analysis:run",
        "component:read",
        "component:update",
        "dashboard:read",
        "lifecycle:override",
        "lifecycle:provider:read",
        "lifecycle:provider:test",
        "lifecycle:read",
        "lifecycle:vendor-record:read",
        "product:assign_sbom",
        "product:manage_schedule",
        "product:read",
        "project:create",
        "project:read",
        "project:update",
        "remediation:close",
        "remediation:read",
        "remediation:write",
        "sbom:export",
        "sbom:read",
        "sbom:repair:download",
        "sbom:repair:read",
        "sbom:repair:revalidate",
        "sbom:repair:search",
        "sbom:repair:update",
        "sbom:update",
        "sbom:upload",
        "schedule:read",
        "schedule:write",
        "vex:read",
        "vex:write",
    ),
    "DEVELOPER": (
        "analysis:read",
        "component:read",
        "dashboard:read",
        "lifecycle:read",
        "product:read",
        "project:read",
        "remediation:read",
        "remediation:write",
        "sbom:read",
        "sbom:repair:read",
        "sbom:repair:search",
        "schedule:read",
        "vex:read",
    ),
    "VIEWER": (
        "analysis:read",
        "component:read",
        "dashboard:read",
        "lifecycle:read",
        "product:read",
        "project:read",
        "remediation:read",
        "sbom:read",
        "sbom:repair:read",
        "sbom:repair:search",
        "schedule:read",
        "vex:read",
    ),
}

ROLE_SCOPES_V1 = {
    "PLATFORM_ADMIN": "PLATFORM",
    "TENANT_ADMIN": "TENANT",
    "SECURITY_ANALYST": "TENANT",
    "DEVELOPER": "TENANT",
    "VIEWER": "TENANT",
}

PROTECTED_ROLE_PERMISSIONS_V1 = {
    "PLATFORM_ADMIN": (
        "platform:admin",
        "platform:administrator:grant",
        "platform:administrator:read",
        "platform:administrator:revoke",
        "platform:authorization:manage",
        "platform:authorization:read",
        "platform:tenant:create",
        "platform:user:manage_status",
        "platform:user:read",
    ),
    "TENANT_ADMIN": (
        "tenant:settings:update",
        "tenant:user:invite",
        "tenant:user:read",
        "tenant:user:update",
    ),
}
