"""Render `docs/validation-error-codes.md` from `app/validation/errors.py`.

The hand-maintained reference under `docs/validation-error-codes.md` is the
*authoritative* description text. This script regenerates the **machine
table** at the bottom (code, status, severity, stage band) from the
`_CODE_TABLE` constant so the doc cannot drift away from the implementation
without a CI failure.

Usage::

    python scripts/gen_error_code_reference.py [--check]

``--check`` exits non-zero if the doc is out of sync with the source.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DOC_PATH = REPO_ROOT / "docs" / "validation-error-codes.md"
SECTION_BEGIN = "<!-- AUTO-GENERATED:BEGIN code-table -->"
SECTION_END = "<!-- AUTO-GENERATED:END code-table -->"


def _stage_band(code: str) -> str:
    """Return a human-readable stage label from the numeric code segment."""
    match = re.search(r"_[EWI](\d{3})_", code)
    if not match:
        return "?"
    n = int(match.group(1))
    if n < 10:
        return "1 ingress"
    if n < 20:
        return "2 detect"
    if n < 40:
        return "3 schema"
    if n < 70:
        return "4 semantic"
    if n < 80:
        return "5 integrity"
    if n < 100:
        return "6 security"
    if n < 110:
        return "7 ntia"
    return "8 signature"


def render_table() -> str:
    sys.path.insert(0, str(REPO_ROOT))
    from app.validation.errors import _CODE_TABLE  # type: ignore[attr-defined]

    rows = sorted(_CODE_TABLE.items())
    lines = [
        SECTION_BEGIN,
        "",
        "| Code | HTTP | Default severity | Stage |",
        "|---|---|---|---|",
    ]
    for code, (status, severity) in rows:
        lines.append(f"| `{code}` | {status} | `{severity.value}` | {_stage_band(code)} |")
    lines.append("")
    lines.append(f"_Generated by `scripts/gen_error_code_reference.py` from `app/validation/errors.py`. "
                 f"{len(rows)} codes total._")
    lines.append("")
    lines.append(SECTION_END)
    return "\n".join(lines)


def update_doc(check_only: bool = False) -> int:
    if not DOC_PATH.exists():
        print(f"error: {DOC_PATH} not found", file=sys.stderr)
        return 2

    current = DOC_PATH.read_text(encoding="utf-8")
    rendered = render_table()

    if SECTION_BEGIN not in current:
        # Append the section if missing.
        new = current.rstrip() + "\n\n## Auto-generated machine table\n\n" + rendered + "\n"
    else:
        new = re.sub(
            re.escape(SECTION_BEGIN) + ".*?" + re.escape(SECTION_END),
            rendered,
            current,
            count=1,
            flags=re.DOTALL,
        )

    if new == current:
        print("error-code reference is up to date.")
        return 0
    if check_only:
        print(f"error: {DOC_PATH.name} is out of sync. Run "
              "`python scripts/gen_error_code_reference.py` and commit.",
              file=sys.stderr)
        return 1

    DOC_PATH.write_text(new, encoding="utf-8")
    print(f"updated {DOC_PATH}")
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="Exit non-zero if the doc is out of sync.")
    args = parser.parse_args()
    sys.exit(update_doc(check_only=args.check))
