"""Central identity state, next-action, error, and audit vocabularies."""

from __future__ import annotations

from enum import StrEnum

from fastapi import HTTPException


class AuthorizationState(StrEnum):
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
    ACCOUNT_PENDING_APPROVAL = "ACCOUNT_PENDING_APPROVAL"
    VERIFICATION_REQUIRED = "VERIFICATION_REQUIRED"
    NO_TENANT = "NO_TENANT"
    TENANT_SELECTION_REQUIRED = "TENANT_SELECTION_REQUIRED"
    READY = "READY"


class NextAction(StrEnum):
    CONTACT_SUPPORT = "CONTACT_SUPPORT"
    WAIT_FOR_APPROVAL = "WAIT_FOR_APPROVAL"
    VERIFY_EMAIL = "VERIFY_EMAIL"
    CONTACT_ADMIN = "CONTACT_ADMIN"
    SELECT_TENANT = "SELECT_TENANT"
    OPEN_PLATFORM_ADMIN = "OPEN_PLATFORM_ADMIN"
    OPEN_DASHBOARD = "OPEN_DASHBOARD"


class IdentityErrorCode(StrEnum):
    ACCOUNT_DISABLED = "IAM_ACCOUNT_DISABLED"
    ACCOUNT_PENDING_APPROVAL = "IAM_ACCOUNT_PENDING_APPROVAL"
    EMAIL_VERIFICATION_REQUIRED = "IAM_EMAIL_VERIFICATION_REQUIRED"
    NO_TENANT = "IAM_NO_TENANT"
    TENANT_SELECTION_REQUIRED = "IAM_TENANT_SELECTION_REQUIRED"
    UNAUTHORIZED_TENANT = "IAM_UNAUTHORIZED_TENANT"
    REQUIRED_CLAIM_MISSING = "IAM_REQUIRED_CLAIM_MISSING"
    IDENTITY_CONFLICT = "IAM_IDENTITY_CONFLICT"
    PROVISIONING_FAILED = "IAM_PROVISIONING_FAILED"
    VERIFICATION_ALREADY_COMPLETED = "IAM_VERIFICATION_ALREADY_COMPLETED"
    VERIFICATION_TOKEN_INVALID = "IAM_VERIFICATION_TOKEN_INVALID"
    VERIFICATION_RESEND_RATE_LIMITED = "IAM_VERIFICATION_RESEND_RATE_LIMITED"
    VERIFICATION_DELIVERY_FAILED = "IAM_VERIFICATION_DELIVERY_FAILED"
    USER_NOT_FOUND = "IAM_USER_NOT_FOUND"
    USER_STATUS_INVALID = "IAM_USER_STATUS_INVALID"
    USER_STATUS_TRANSITION_NOT_ALLOWED = "IAM_USER_STATUS_TRANSITION_NOT_ALLOWED"
    PLATFORM_ADMIN_ALREADY_GRANTED = "IAM_PLATFORM_ADMIN_ALREADY_GRANTED"
    PLATFORM_ADMIN_NOT_GRANTED = "IAM_PLATFORM_ADMIN_NOT_GRANTED"
    PLATFORM_ADMIN_GRANT_INELIGIBLE = "IAM_PLATFORM_ADMIN_GRANT_INELIGIBLE"
    LAST_PLATFORM_ADMIN_PROTECTED = "IAM_LAST_PLATFORM_ADMIN_PROTECTED"
    PLATFORM_PERMISSION_DENIED = "IAM_PLATFORM_PERMISSION_DENIED"
    PLATFORM_ADMIN_BOOTSTRAP_REQUIRED = "IAM_PLATFORM_ADMIN_BOOTSTRAP_REQUIRED"
    PLATFORM_ADMIN_BOOTSTRAP_CONFLICT = "IAM_PLATFORM_ADMIN_BOOTSTRAP_CONFLICT"
    TENANT_NAME_INVALID = "IAM_TENANT_NAME_INVALID"
    TENANT_SLUG_INVALID = "IAM_TENANT_SLUG_INVALID"
    TENANT_SLUG_CONFLICT = "IAM_TENANT_SLUG_CONFLICT"
    TENANT_EXTERNAL_ID_CONFLICT = "IAM_TENANT_EXTERNAL_ID_CONFLICT"
    TENANT_CREATION_FAILED = "IAM_TENANT_CREATION_FAILED"
    INITIAL_TENANT_ADMIN_REQUIRED = "IAM_INITIAL_TENANT_ADMIN_REQUIRED"
    INITIAL_TENANT_ADMIN_NOT_FOUND = "IAM_INITIAL_TENANT_ADMIN_NOT_FOUND"
    INITIAL_TENANT_ADMIN_INELIGIBLE = "IAM_INITIAL_TENANT_ADMIN_INELIGIBLE"
    INITIAL_TENANT_ADMIN_ASSIGNMENT_FAILED = (
        "IAM_INITIAL_TENANT_ADMIN_ASSIGNMENT_FAILED"
    )
    AUTHORIZATION_CATALOG_UNAVAILABLE = "IAM_AUTHORIZATION_CATALOG_UNAVAILABLE"
    AUTHORIZATION_CATALOG_INCOMPLETE = "IAM_AUTHORIZATION_CATALOG_INCOMPLETE"
    AUTHORIZATION_CATALOG_MISMATCH = "IAM_AUTHORIZATION_CATALOG_MISMATCH"
    ROLE_NOT_FOUND = "IAM_ROLE_NOT_FOUND"
    ROLE_SYSTEM_IMMUTABLE = "IAM_ROLE_SYSTEM_IMMUTABLE"
    ROLE_VERSION_CONFLICT = "IAM_ROLE_VERSION_CONFLICT"
    PERMISSION_NOT_FOUND = "IAM_PERMISSION_NOT_FOUND"
    PERMISSION_STATUS_INVALID = "IAM_PERMISSION_STATUS_INVALID"
    PERMISSION_CODE_INVALID = "IAM_PERMISSION_CODE_INVALID"
    ROLE_PERMISSION_SCOPE_MISMATCH = "IAM_ROLE_PERMISSION_SCOPE_MISMATCH"
    PROTECTED_PERMISSION_MAPPING = "IAM_PROTECTED_PERMISSION_MAPPING"
    ROLE_PERMISSION_UPDATE_FAILED = "IAM_ROLE_PERMISSION_UPDATE_FAILED"
    TENANT_ROLE_ASSIGNMENT_NOT_FOUND = "IAM_TENANT_ROLE_ASSIGNMENT_NOT_FOUND"
    TENANT_MEMBERSHIP_NOT_FOUND = "IAM_TENANT_MEMBERSHIP_NOT_FOUND"
    TENANT_ROLE_ALREADY_ASSIGNED = "IAM_TENANT_ROLE_ALREADY_ASSIGNED"
    TENANT_ROLE_NOT_ASSIGNABLE = "IAM_TENANT_ROLE_NOT_ASSIGNABLE"
    TENANT_ROLE_SCOPE_MISMATCH = "IAM_TENANT_ROLE_SCOPE_MISMATCH"
    TENANT_ROLE_DISABLED = "IAM_TENANT_ROLE_DISABLED"
    TENANT_ROLE_VERSION_CONFLICT = "IAM_TENANT_ROLE_VERSION_CONFLICT"
    TENANT_ROLE_SET_EMPTY = "IAM_TENANT_ROLE_SET_EMPTY"
    ACTIVE_MEMBERSHIP_REQUIRES_ROLE = "IAM_ACTIVE_MEMBERSHIP_REQUIRES_ROLE"
    MULTI_ROLE_COMPATIBILITY_CONFLICT = "IAM_MULTI_ROLE_COMPATIBILITY_CONFLICT"
    PRIMARY_TENANT_ROLE_REQUIRED = "IAM_PRIMARY_TENANT_ROLE_REQUIRED"
    PRIMARY_TENANT_ROLE_REPLACEMENT_REQUIRED = (
        "IAM_PRIMARY_TENANT_ROLE_REPLACEMENT_REQUIRED"
    )
    TENANT_ROLE_ASSIGNMENT_FAILED = "IAM_TENANT_ROLE_ASSIGNMENT_FAILED"
    TENANT_ROLE_HISTORY_ACCESS_DENIED = "IAM_TENANT_ROLE_HISTORY_ACCESS_DENIED"
    TENANT_ROLE_ASSIGNMENT_DATA_INCOMPLETE = (
        "IAM_TENANT_ROLE_ASSIGNMENT_DATA_INCOMPLETE"
    )
    LAST_TENANT_ADMIN_PROTECTED = "IAM_LAST_TENANT_ADMIN_PROTECTED"


class IdentityAuditEvent(StrEnum):
    USER_PROVISIONED = "IAM_USER_PROVISIONED"
    USER_PROVISIONING_FAILED = "IAM_USER_PROVISIONING_FAILED"
    EXTERNAL_IDENTITY_LINKED = "IAM_EXTERNAL_IDENTITY_LINKED"
    IDENTITY_CONFLICT = "IAM_IDENTITY_CONFLICT"
    CLAIMS_SYNCHRONIZED = "IAM_CLAIMS_SYNCHRONIZED"
    EMAIL_CHANGED = "IAM_EMAIL_CHANGED"
    REVERIFICATION_REQUIRED = "IAM_REVERIFICATION_REQUIRED"
    AUTH_CONTEXT_RESOLVED = "IAM_AUTH_CONTEXT_RESOLVED"
    ACCESS_BLOCKED_DISABLED = "IAM_ACCESS_BLOCKED_DISABLED"
    ACCESS_BLOCKED_PENDING = "IAM_ACCESS_BLOCKED_PENDING"
    ACCESS_BLOCKED_UNVERIFIED = "IAM_ACCESS_BLOCKED_UNVERIFIED"
    NO_TENANT = "IAM_NO_TENANT"
    TENANT_SELECTION_REQUIRED = "IAM_TENANT_SELECTION_REQUIRED"
    UNAUTHORIZED_TENANT_SELECTION = "IAM_UNAUTHORIZED_TENANT_SELECTION"
    VERIFICATION_TOKEN_CREATED = "IAM_VERIFICATION_TOKEN_CREATED"
    VERIFICATION_TOKEN_INVALIDATED = "IAM_VERIFICATION_TOKEN_INVALIDATED"
    VERIFICATION_EMAIL_SENT = "IAM_VERIFICATION_EMAIL_SENT"
    VERIFICATION_EMAIL_FAILED = "IAM_VERIFICATION_EMAIL_FAILED"
    VERIFICATION_RESEND_REQUESTED = "IAM_VERIFICATION_RESEND_REQUESTED"
    VERIFICATION_RESEND_RATE_LIMITED = "IAM_VERIFICATION_RESEND_RATE_LIMITED"
    EMAIL_VERIFICATION_SUCCEEDED = "IAM_EMAIL_VERIFICATION_SUCCEEDED"
    EMAIL_VERIFICATION_FAILED = "IAM_EMAIL_VERIFICATION_FAILED"
    EMAIL_VERIFICATION_REPLAY_REJECTED = "IAM_EMAIL_VERIFICATION_REPLAY_REJECTED"
    EMAIL_VERIFICATION_EXPIRED = "IAM_EMAIL_VERIFICATION_EXPIRED"
    EMAIL_VERIFICATION_EMAIL_MISMATCH = "IAM_EMAIL_VERIFICATION_EMAIL_MISMATCH"
    PLATFORM_USER_LIST_VIEWED = "PLATFORM_USER_LIST_VIEWED"
    PLATFORM_USER_DETAIL_VIEWED = "PLATFORM_USER_DETAIL_VIEWED"
    PLATFORM_USER_STATUS_CHANGED = "PLATFORM_USER_STATUS_CHANGED"
    PLATFORM_USER_ACTIVATED = "PLATFORM_USER_ACTIVATED"
    PLATFORM_USER_DISABLED = "PLATFORM_USER_DISABLED"
    PLATFORM_USER_REACTIVATED = "PLATFORM_USER_REACTIVATED"
    PLATFORM_ADMIN_LIST_VIEWED = "PLATFORM_ADMIN_LIST_VIEWED"
    PLATFORM_ADMIN_GRANTED = "PLATFORM_ADMIN_GRANTED"
    PLATFORM_ADMIN_GRANT_REACTIVATED = "PLATFORM_ADMIN_GRANT_REACTIVATED"
    PLATFORM_ADMIN_REVOKED = "PLATFORM_ADMIN_REVOKED"
    PLATFORM_ADMIN_GRANT_REJECTED = "PLATFORM_ADMIN_GRANT_REJECTED"
    PLATFORM_ADMIN_LAST_ADMIN_PROTECTED = "PLATFORM_ADMIN_LAST_ADMIN_PROTECTED"
    PLATFORM_ADMIN_BOOTSTRAPPED = "PLATFORM_ADMIN_BOOTSTRAPPED"
    PLATFORM_ADMIN_BOOTSTRAP_REJECTED = "PLATFORM_ADMIN_BOOTSTRAP_REJECTED"
    PLATFORM_TENANT_CREATE_REQUESTED = "PLATFORM_TENANT_CREATE_REQUESTED"
    PLATFORM_TENANT_CREATED = "PLATFORM_TENANT_CREATED"
    PLATFORM_TENANT_CREATE_FAILED = "PLATFORM_TENANT_CREATE_FAILED"
    TENANT_INITIAL_ADMIN_VALIDATED = "TENANT_INITIAL_ADMIN_VALIDATED"
    TENANT_INITIAL_ADMIN_ASSIGNED = "TENANT_INITIAL_ADMIN_ASSIGNED"
    TENANT_INITIAL_ADMIN_ASSIGNMENT_FAILED = (
        "TENANT_INITIAL_ADMIN_ASSIGNMENT_FAILED"
    )
    TENANT_CREATION_ROLLED_BACK = "TENANT_CREATION_ROLLED_BACK"
    TENANT_SLUG_CONFLICT = "TENANT_SLUG_CONFLICT"
    TENANT_EXTERNAL_ID_CONFLICT = "TENANT_EXTERNAL_ID_CONFLICT"
    AUTHORIZATION_CATALOG_VIEWED = "AUTHORIZATION_CATALOG_VIEWED"
    AUTHORIZATION_ROLE_VIEWED = "AUTHORIZATION_ROLE_VIEWED"
    AUTHORIZATION_PERMISSION_VIEWED = "AUTHORIZATION_PERMISSION_VIEWED"
    AUTHORIZATION_MATRIX_VIEWED = "AUTHORIZATION_MATRIX_VIEWED"
    AUTHORIZATION_ROLE_UPDATED = "AUTHORIZATION_ROLE_UPDATED"
    AUTHORIZATION_ROLE_UPDATE_REJECTED = "AUTHORIZATION_ROLE_UPDATE_REJECTED"
    AUTHORIZATION_ROLE_PERMISSIONS_UPDATED = "AUTHORIZATION_ROLE_PERMISSIONS_UPDATED"
    AUTHORIZATION_ROLE_PERMISSIONS_UPDATE_REJECTED = (
        "AUTHORIZATION_ROLE_PERMISSIONS_UPDATE_REJECTED"
    )
    AUTHORIZATION_PROTECTED_PERMISSION_REMOVAL_REJECTED = (
        "AUTHORIZATION_PROTECTED_PERMISSION_REMOVAL_REJECTED"
    )
    AUTHORIZATION_SCOPE_MISMATCH_REJECTED = "AUTHORIZATION_SCOPE_MISMATCH_REJECTED"
    AUTHORIZATION_VERSION_CONFLICT = "AUTHORIZATION_VERSION_CONFLICT"
    AUTHORIZATION_CATALOG_MISMATCH_DETECTED = (
        "AUTHORIZATION_CATALOG_MISMATCH_DETECTED"
    )
    AUTHORIZATION_CATALOG_MISSING_ROLE = "AUTHORIZATION_CATALOG_MISSING_ROLE"
    AUTHORIZATION_CATALOG_MISSING_PERMISSION = (
        "AUTHORIZATION_CATALOG_MISSING_PERMISSION"
    )
    AUTHORIZATION_CATALOG_SEEDED = "AUTHORIZATION_CATALOG_SEEDED"
    TENANT_ROLE_ASSIGNMENT_GRANTED = "TENANT_ROLE_ASSIGNMENT_GRANTED"
    TENANT_ROLE_ASSIGNMENT_REACTIVATED = "TENANT_ROLE_ASSIGNMENT_REACTIVATED"
    TENANT_ROLE_ASSIGNMENT_REVOKED = "TENANT_ROLE_ASSIGNMENT_REVOKED"
    TENANT_ROLE_PRIMARY_CHANGED = "TENANT_ROLE_PRIMARY_CHANGED"
    TENANT_ROLE_SET_REPLACED = "TENANT_ROLE_SET_REPLACED"
    TENANT_ROLE_ASSIGNMENT_REJECTED = "TENANT_ROLE_ASSIGNMENT_REJECTED"
    TENANT_ROLE_VERSION_CONFLICT = "TENANT_ROLE_VERSION_CONFLICT"
    TENANT_ROLE_SCOPE_REJECTED = "TENANT_ROLE_SCOPE_REJECTED"
    TENANT_ROLE_NOT_ASSIGNABLE = "TENANT_ROLE_NOT_ASSIGNABLE"
    TENANT_ROLE_LAST_ADMIN_PROTECTED = "TENANT_ROLE_LAST_ADMIN_PROTECTED"
    TENANT_ROLE_HISTORY_VIEWED = "TENANT_ROLE_HISTORY_VIEWED"
    TENANT_ROLE_ASSIGNMENT_MIGRATED = "TENANT_ROLE_ASSIGNMENT_MIGRATED"


def identity_http_error(
    code: IdentityErrorCode,
    message: str,
    *,
    status_code: int = 403,
) -> HTTPException:
    return HTTPException(
        status_code=status_code,
        detail={"code": str(code), "message": message},
    )
